### ISSUE TITLE
Number system calculator

### ISSUE THREAD

**Issue by nitishkumar07** [vasu-1/CalcHub#1]
### Calculator Functions

conversion for decimal to binary,octal,hexadecimal and vice versa.
I am  contributor in  GSSOC-22
can you assign this issue to me?

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
sure, this issue will be assigned to you! but start the coding part after the contribution period starts!
I will assign this issue to you by tomorrow!!

**Comment by vasu-1** [comment]
You can assign this issue to youself by typing `/assign` in the comment !!
