### ISSUE TITLE
Log calculator

### ISSUE THREAD

**Issue by Siddhesh777** [vasu-1/CalcHub#100]
### Calculator Functions

**Description**
This calculator is used to calculate the log value to the base b(2,10,e).
we will be able to calculate the value of logb(x),where b and x will be taken as input from user

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by satyam1511** [comment]
/assign
Under GSSoC22.

**Comment by Siddhesh777** [comment]
hey @satyam1511 
I think it has not been assigned to me yet.
Can you please assign this issue to me?
