### ISSUE TITLE
Clicking the image to open link in new tab

### ISSUE THREAD

**Issue by Yasshu55** [vasu-1/CalcHub#106]
When a user clicks any of the following tabs the page opens in the current tab 
![newtab](https://user-images.githubusercontent.com/95294297/156922290-48b68590-42e3-414a-9924-83b9eaa5d4e0.PNG)

I would like to change the code to open the page in New tab

**Comment by vasu-1** [comment]
No Need for this as of now !!

You can create another issue for a unique calculators !!

Thanks !!
