### ISSUE TITLE
Scientific Calculator

### ISSUE THREAD

**Issue by anu-oss** [vasu-1/CalcHub#11]
### Calculator Functions

This scientific calculator performs functions beyond addition, subtraction, multiplication and division. AA scientific calculator usually has special buttons for parentheses, trigonometric functions, exponents, inverses and pi -- among other things. All the mathematical operation you can run on this online calculator. 

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
I can see there is already one scientific calculator in the repo !
If you can implement extra features in your calculator than only work on this issue !

Thank you !

**Comment by vasu-1** [comment]
@anu-oss 
Only work on one issue at a time !!!!!!!!!!!!

And each calculator must be unique !!

**Comment by anu-oss** [comment]
@vasu-1 what is the deadline for each issue?

**Comment by vasu-1** [comment]
ig, till contribution period ends !

Instructions will be provided soon !!

`Work on the issue after tomorrow !!`

**Comment by anu-oss** [comment]
great. also, given that scientific calculator has been taken up, can I close this issue and open a different one?

**Comment by vasu-1** [comment]
yes !!

**Comment by anu-oss** [comment]
thanks.
