### ISSUE TITLE
New UI  and enhancement of simple calculator

### ISSUE THREAD

**Issue by maharshi-sinha** [vasu-1/CalcHub#115]
![Screenshot (288)](https://user-images.githubusercontent.com/72745563/157005272-9f2d7c3a-db59-43ce-9720-42b626dcc769.png)

**Comment by Manik-Aggarwal** [comment]
Please assign it to me

**Comment by Bhavesh66** [comment]
Please assign it to me.

**Comment by satyam1511** [comment]
Hi @maharshi-sinha I would like to work on this issue. Please assign it to me.
