### ISSUE TITLE
Simple Arithmetic Calculator

### ISSUE THREAD

**Issue by anu-oss** [vasu-1/CalcHub#13]
### Calculator Functions

Functionalities :-
Addition
Subtraction
Division
Multiplication

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
It is already there in the repo !
You can't create duplicate calculator !
`Work only on one issue at a time !`
Deleting this issue !

**Comment by anu-oss** [comment]
Hi there @vasu-1 .
 My bad.
