### ISSUE TITLE
Matrix Calculator

### ISSUE THREAD

**Issue by BIKRAM-SAHA** [vasu-1/CalcHub#147]
### Calculator Functions

This calculator will perform simple arithmetic operations like addition, subtraction or multiplication on 2 matrices
.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by KhushiRana2003** [comment]
Please assign this to me i want to work on this issue and i am gssoc partitcipant 2022
