### ISSUE TITLE
styling homepage

### ISSUE THREAD

**Issue by RiyaJain12** [vasu-1/CalcHub#151]
### Calculator Functions

I want to do some changes in the homepage of the website and wants to make it more attractive!
please assign me!

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by Richadxt** [comment]
I also want to make some changes in the homepage of the website and wants to make this website unique and more attractive....please assign me to work on this issue.
