### ISSUE TITLE
Binary Calculator

### ISSUE THREAD

**Issue by R-Ayush777** [vasu-1/CalcHub#153]
### Calculator Functions

I'd like to make some changes to the binary calculator, such as creating a nice user interface and making it more appealing, as well as adding binary results along with their decimal and hex values.
please assign me!

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by pushpanjali-10** [comment]
please assign me!

**Comment by Sourajita21** [comment]
Can you assign this to me. I will give my best for sure.
