### ISSUE TITLE
BMI Calculator 

### ISSUE THREAD

**Issue by SO1ee** [vasu-1/CalcHub#154]
### Calculator Functions

This calculator will help to calculate BMI and it will show the result. 

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by rithik-sharma** [comment]
@SO1ee good go ahead !!!!!
