### ISSUE TITLE
centimeter-meter to foot-inches converter

### ISSUE THREAD

**Issue by Siddhesh777** [vasu-1/CalcHub#171]
### Calculator Functions

I want to make a calculator which will convert cm/m to foot/inches and vice versa.
Because in day-to-day life the inter-conversion of these is needed many times.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by itsMahakA** [comment]
I want to work on this issue, please assign it to me

**Comment by pushpanjali-10** [comment]
Hey, I am a contributor of GSSoc'22. Can you assign me this issue ?

**Comment by komalsoni4** [comment]
please assign this issue to me
