### ISSUE TITLE
Construction cost calculator

### ISSUE THREAD

**Issue by Siddhesh777** [vasu-1/CalcHub#172]
### Calculator Functions

I want to make a calculator which will give total cost of construction.
User have to give total no of sq.ft area to be constructed and rate of construction (per sq.ft)
We will display the total cost needed.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by pushpanjali-10** [comment]
Hey, I am a contributor of GSSoc'22. Can you assign me this issue ?

**Comment by komalsoni4** [comment]
please assign this issue to me
