### ISSUE TITLE
Daily Water intake calculator 

### ISSUE THREAD

**Issue by MonarchGitHub** [vasu-1/CalcHub#183]
### Calculator Functions

This will be useful to determine the **_amount of water_** the user must drink each day to **_avoid dehydration_**. This calculator will estimate this based on the factors such as: 

- **Weight**
- **Amount of activity**
- **Climate**

It will also have suggestions tailored to the user's choice.
The UI of this calculator will be minimal, calming, and easy to use.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by MonarchGitHub** [comment]
Kindly assign me this issue.

**Comment by PraveenaPulagam** [comment]
Is this issue is still open?If Yes..Could you please assign me?
