### ISSUE TITLE
[Create New Issue]: A Scientific Calculator with better UI 

### ISSUE THREAD

**Issue by Jyo561** [vasu-1/CalcHub#19]
### Calculator Functions

Description: I can improve the ui of the existing calculators

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
No need for better ui !
Pick the calculator that is not existing in the repo. !

Thanks !
