### ISSUE TITLE
[Create New Issue]: Matrix Adjoint and Inverse Calculator

### ISSUE THREAD

**Issue by kaustav202** [vasu-1/CalcHub#2]
### Calculator Functions

Take User Input Matrix and display the Adjoint and Inverse of that matrix.

I would like to work on this issue can you assign this to me.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by Kushal-2002** [comment]
I am a GSSOC'22 participant, I want to work on this issue.

**Comment by vasu-1** [comment]
You can assign this issue to youself by typing `/assign` in the comment !!
