### ISSUE TITLE
Radix Converter 

### ISSUE THREAD

**Issue by miretteamin** [vasu-1/CalcHub#201]
### Calculator Functions

Description

Convert from different radix to another (any base to another).

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by PraveenaPulagam** [comment]
Could you please assign me this issue?
