### ISSUE TITLE
[Create New Issue]:  Logical operations calculator

### ISSUE THREAD

**Issue by Akriti-007** [vasu-1/CalcHub#203]
### Calculator Functions

Description I am GSSoC 2022 contributor. I would like to add a calculator that performs logical operations like AND, OR and NOT. It also includes bitwise operations.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by PraveenaPulagam** [comment]
could you please assign me this issue under GSSOC'22.?

**Comment by komalsoni4** [comment]
please assign this issue to me
