### ISSUE TITLE
VAT_Calculator

### ISSUE THREAD

**Issue by codingkush** [vasu-1/CalcHub#205]
### Calculator Functions

Description : Hello, I am a contributor in GSSOC' 22. I want to make VAT Calculator that  calculates the Value Added Tax (VAT) on products or services.

This calculator has two input fields, one for amount and another one for vat rate and two output fields , one is for VAT amount and another one for VAT Inclusive amount.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by codingkush** [comment]
I want to work on this .pls assign me this issue under GSsoc 22.

**Comment by komalsoni4** [comment]
please assign this issue to me
