### ISSUE TITLE
Graphing calculator 

### ISSUE THREAD

**Issue by Ashkul23** [vasu-1/CalcHub#21]
### Calculator Functions

graphing calculator is a scientific calculator with a high resolution screen and includes the ability to plot coordinates and graph functions.
A graphing calculator is a handheld computer that is capable of plotting graphs, solving simultaneous equations, and performing other tasks with variables.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vai-shali** [comment]
Hi can I work on this issue for gssoc'22?
