### ISSUE TITLE
RSA Encryptor Calculator

### ISSUE THREAD

**Issue by BabyElias** [vasu-1/CalcHub#217]
### Calculator Functions

It is a calculator based on the RSA Public Key Encryption/Decryption scheme.RSA is an asymmetric algorithm for public-key cryptography. A private and public key is created, with the public key being accessible to anyone and the private key is a secret known only by the key pair creator. With RSA, the private or public key can encrypt the data while the other key decrypts it. It is the most used in data exchange over the Internet.
I would try to provide the backend using C++.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by komalsoni4** [comment]
please assign this issue to me
