### ISSUE TITLE
Adding Logo and Animation Effects 

### ISSUE THREAD

**Issue by geetanjali2001** [vasu-1/CalcHub#225]
### Calculator Functions

Hi,
I want to add logo and animation effects in title of website which make it more attractive.
![Screenshot (16)_LI](https://user-images.githubusercontent.com/100347557/162183137-50b64e50-d1f8-4a21-a4d5-0b5399fcf17f.jpg)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by Anjalih11** [comment]
Sir can you assign this to me I am a GSSOC 2022 contributer and I with add the logo and animation effects of title of website by using CSS please assign this to me I will do the best change of it

**Comment by komalsoni4** [comment]
please assign this issue to me

**Comment by aachal28** [comment]
Kindly assign me this issue
