### ISSUE TITLE
Days Calculator: Days between two dates 

### ISSUE THREAD

**Issue by Surajkarle77** [vasu-1/CalcHub#23]
### Calculator Functions

The main objectives of this project is to calculate the days, time  between two dates . 

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
You cannot work on this such a small task !
This can hardly take 5-10 mins to build .
Kindly think of better idea ! or you can do something unique in this issue !!!!!
