### ISSUE TITLE
[Create New Issue]:  Add Area Calculator

### ISSUE THREAD

**Issue by Anish-Parkhi** [vasu-1/CalcHub#238]
### Calculator Functions

I want to add area calculator which will take respective inputs and it will calculate area.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by riyajaiswal25** [comment]
I want to work on this.

**Comment by riyajaiswal25** [comment]
i want to work on this.

**Comment by vasu-1** [comment]
> /assign

@Anjalih11   create your own pr!
in case of any queries feel free to reach out to us on discord !

**Comment by komalsoni4** [comment]
please assign this issue o me
