### ISSUE TITLE
Add length converter into different unit calculator

### ISSUE THREAD

**Issue by AsmaIbrahimButt** [vasu-1/CalcHub#242]
### Calculator Functions

I want to add a length converter tool if a user enter length in cm it would convert into inches and feet and other units too.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by riyajaiswal25** [comment]
I want to work on this.

**Comment by PraveenaPulagam** [comment]
Could you please assign this issue to me ?I would like to work on this.

**Comment by AsmaIbrahimButt** [comment]
@riyajaiswal25 @PraveenaPulagam Im already work on this .
