### ISSUE TITLE
Resistance Calculator using Ohm's Law

### ISSUE THREAD

**Issue by Mrjoy832** [vasu-1/CalcHub#249]
### Calculator Functions

**Description**
Ohm’s law states that the voltage across a conductor is directly proportional to the current flowing through it, provided all physical conditions and temperature remain constant.
Mathematically, this current-voltage relationship is written as, **V=IR**. With this the calculator will determine resistance within a given circuit.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by navyasharma0203** [comment]
If this issue isn't closed yet, can I work on this??

**Comment by Mrjoy832** [comment]
> If this issue isn't closed yet, can I work on this??

I will make don't worry, make your own
