### ISSUE TITLE
Improve Simple Calculator

### ISSUE THREAD

**Issue by devgirlcodes** [vasu-1/CalcHub#26]
### Calculator Functions

**Problem**
The buttons in [Simple Calculator](https://vashishth.me/CalcHub/Calculators/Simple_Arithmetic/) are not in a manner that makes user experience easy. 
![Screenshot 2022-03-01 114214](https://user-images.githubusercontent.com/99732684/156115378-69d5f05e-4655-465a-95ba-6e025a6159ba.png)

**Improvement Suggested**
I want to re-arrange how the buttons appear on the calculator

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
For now, You just need to make the new unique calculator.
No editing or duplicate calculator are allowed (for now)

Thanks for your interest !!

**Comment by devgirlcodes** [comment]
Okay
