### ISSUE TITLE
Income Tax Calculator

### ISSUE THREAD

**Issue by DragonUncaged** [vasu-1/CalcHub#276]
### Calculator Functions

From The Input Amount (in Rs)
it Will Calculate the Indian Tax.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
@DragonUncaged assign this issue to yourself using `/assign`

**Comment by komalsoni4** [comment]
please assign this issue to me
