### ISSUE TITLE
Velocity Calculator

### ISSUE THREAD

**Issue by iamrahulmahato** [vasu-1/CalcHub#284]
### Calculator Functions

By entering any three quantities it will evaluate the fourth one.

![Web capture_4-5-2022_213125_127 0 0 1](https://user-images.githubusercontent.com/49890655/166864220-f28cdcee-9d73-4872-a141-5cc76e8e57f2.jpeg)

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by sharma-tanishq** [comment]
Hi I am a GSSOC22 contributer can i work on this?

**Comment by sharma-tanishq** [comment]
can only owner get assigned to the issue???

**Comment by iamrahulmahato** [comment]
@vasu-1 the pr is made #290
