### ISSUE TITLE
Protein Calculator

### ISSUE THREAD

**Issue by Anjalih11** [vasu-1/CalcHub#285]
### Calculator Functions

The Protein Calculator estimates the daily amount of dietary protein adults require to remain healthy. Children, those who are highly physically active, and pregnant and nursing women typically require more protein. The calculator is also useful for monitoring protein intake for those with kidney disease, liver disease, diabetes, or other conditions in which protein intake is a factor.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by sharma-tanishq** [comment]
Hi I am a GSSOC22 contributer can i work on this?
