### ISSUE TITLE
binomial coefficient calculator

### ISSUE THREAD

**Issue by 14anirudh** [vasu-1/CalcHub#296]
### Calculator Functions

this calculator is used for calculating the value of binomial coefficient by taking the values of n and k from the user and returns the answer.if there is any discrepancy that too will be displayed.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
@14anirudh assign this issue to yourself using `/assign`

**Comment by 14anirudh** [comment]
Please merge this
