### ISSUE TITLE
Here to make in percentage calculator 

### ISSUE THREAD

**Issue by aman-7299** [vasu-1/CalcHub#299]
### Calculator Functions

Here to make online calculator which is helpful find  percentage 

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
@aman-7299 assign this issue to yourself using `/assign`
