### ISSUE TITLE
Loan Calculator

### ISSUE THREAD

**Issue by abhi1e9-1e10** [vasu-1/CalcHub#3]
### Calculator Functions

The main objective of this project is to calculate and displays the results for monthly payment, total payment, and total interest according to loan amount interest rate, and years to repay.
Key concepts covered :-

1.) document.querySelector()
2.) setInterval()
3.) Math.pow()
4.) toFixed()
5.) parseFloat()
6.) DOM manipulation
7.) JavaScript CSS Manipulation
8.) eventListener()

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by Kushal-2002** [comment]
I am a GSSOC'22 participant, I want to work on this issue.

**Comment by vasu-1** [comment]
Don't Open multiple issues at a time ! Please work on one issue and after you can create another one !
you will be assigned to only one issue at a time !!
@abhi1e9-1e10

**Comment by abhi1e9-1e10** [comment]
Ok Sir, But which issue is assigned to me..??

**Comment by vasu-1** [comment]
You can assign this issue to youself by typing `/assign` in the comment !!

**Comment by vaishnavighiradkar** [comment]
> You can assign this issue to yourself by typing `/assign` in the comment !!

unable to do so
