### ISSUE TITLE
 Currency Conversion Calculator

### ISSUE THREAD

**Issue by VagishaGupta9** [vasu-1/CalcHub#31]
### Calculator Functions

I would like to add a currency conversion calculator which can convert any currency to the desired one.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
duplicate #27 
closing this issue !
create another one with a unique idea !
