### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ericdrosado** [vasu-1/CalcHub#315]
You have a great README thus far. I would recommend referencing a code of conduct to make the repo welcoming.

**Comment by vasu-1** [comment]
> > How can I Improve the readme.md by referencing a code of conduct ?
> > Can you please elaborate on this ?
> 
> Sure! You can create a section with a Code of Conduct header, and below it describe that you are following the `Contributor Covenant Code of Conduct`. You can then provide context on why you did this, and why is it important to you and your community to have a code of conduct.

Fine ! Understood !
Thank You!
