### ISSUE TITLE
BMI CALCULATOR[Create New Issue]: 

### ISSUE THREAD

**Issue by aditi10701** [vasu-1/CalcHub#318]
### Calculator Functions

It gives description of the BMI and details regarding the same.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by navyasharma0203** [comment]
Could you please assign this issue to me?? I am interested to work on this :)
