### ISSUE TITLE
[Create New Issue]: VigenereCipher_Calculator

### ISSUE THREAD

**Issue by saiadityaviswanadham** [vasu-1/CalcHub#34]
### Calculator Functions

Created a VigenereCipher Calculator for secure transmission of messages.
The Vigenere cipher is an algorithm that is used to encrypting and decrypting the text. The Vigenere cipher is an algorithm of encrypting an alphabetic text that uses a series of interwoven Caesar ciphers. It is based on a keyword's letters.

Attaching the structure and model of VigenereCipher

![structure_vigenerecipher](https://user-images.githubusercontent.com/71250738/156129160-25fa8cbf-73d2-4ccd-a328-bd39faa82c25.png)
![VigenereCipher_Calculator](https://user-images.githubusercontent.com/71250738/156129165-fbe47d11-cc0f-4aed-aac7-9048a360550a.png)

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by AnIkeT126** [comment]
Can u work on this issue as a part of GSSoC'22?
