### ISSUE TITLE
Compound Interest Calculator.

### ISSUE THREAD

**Issue by Preet-Sojitra** [vasu-1/CalcHub#350]
I have seen the all the calculators in the repository and get to know that compound interest calculator has already been made. I have also made the compound interest calculator with good UI. You can check mine's calculator [here](https://preet-sojitra.github.io/InterestCalculator/). 
Since this type of calculator is already been made, but I want to merge mine if you like the UI. 
So should I open pull request?

**Comment by vasu-1** [comment]
Yes @Preet-Sojitra ! You Can!

**Comment by Preet-Sojitra** [comment]
I will open pull request soon. 
Thank you :)
