### ISSUE TITLE
A complete Scientific calculator

### ISSUE THREAD

**Issue by aarush-paul** [vasu-1/CalcHub#358]
functionalities: trigonometric functions, calculus etc.

**Comment by vasu-1** [comment]
You can edit [this](https://github.com/vasu-1/CalcHub/tree/main/Calculators/Scientific_Calculator)

**Comment by aarush-paul** [comment]
Oh shoot I didn't see that. I'll make sure to update it else I'll be closing the issue. Thanks @vasu-1
