### ISSUE TITLE
[Bug]: 40. Scientific Calculator is not responsive in phone size.

### ISSUE THREAD

**Issue by vasu-1** [vasu-1/CalcHub#365]
### Briefly describe the bug

- Scientific Calculator Is Not Having Responsiveness.
- UI Improvement

### What is the expected behavior?

- Calculator should be responsive in all device sizes.

### Please provide step by step instructions on how to reproduce the bug

- N.A You can come up with your own solution

### Contribution Event

Other

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by vasu-1** [comment]
Anyone can start work on this issue. by simply assigning the issue to yourself.

**Comment by Fer-Bar** [comment]
/assign
Hey @vasu-1  can you assign me this issue? I wanna work in that issue

**Comment by vasu-1** [comment]
>  /assign
> Hey @vasu-1  can you assign me this issue? I wanna work in that issue

You can work on this issue 🙏

**Comment by karantec** [comment]
I want to work on this issue , IF anyone hasn't donw it .
