### ISSUE TITLE
[Bug]: 48 Temperature Calculator || UI Improvement Needed

### ISSUE THREAD

**Issue by vasu-1** [vasu-1/CalcHub#367]
### Briefly describe the bug

Current ui for temparature calculator is not good and also not responsive in all screens.

### What is the expected behavior?

New UI must be better then existing one.
It should be responsive in all screen sizes.
Link of existing calculator: https://vashishth.me/CalcHub/Calculators/Temperature_Calculator/

### Please provide step by step instructions on how to reproduce the bug

You can add new code or edit the existing one.

### Contribution Event

Other

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by vasu-1** [comment]
Anyone can start work on this issue. (just type /assign in the comment. The issue will be assign to the person who comes first.)

**Comment by Smit-05** [comment]
Hey @vasu-1 
Can you please assign this issue to me ?

**Comment by vasu-1** [comment]
> Hey @vasu-1 
> Can you please assign this issue to me ?
> 

Just type /assign in the comment 🎉
