### ISSUE TITLE
 BMI Calculator

### ISSUE THREAD

**Issue by abhi1e9-1e10** [vasu-1/CalcHub#4]
### Calculator Functions

The objective of this JavaScript project is to wire up a very basic JavaScript BMI Calculator.
Key concepts covered :-
1.) document.querySelector()
2.) event listeners
3.) parseInt()
4.) toFixed()
5.) innerHTML

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vaishnavighiradkar** [comment]
I'm a contributor in GSSOC-22.
Can you assign this issue to me?

**Comment by Kushal-2002** [comment]
I am a GSSOC'22 participant, I want to work on this issue. I have previously made BMI calculator using Java Script.

**Comment by Anish1411** [comment]
hey @abhi1e9-1e10
 I am a GSSOC'22 contributor and i want to work on this issue , assign it to me.

**Comment by vasu-1** [comment]
@abhi1e9-1e10  as of now I am deleting this issue as you have already one opened issue !
You can create another issue after your issue will be fixed !
In case of any queries reach out to me on discord !

@Anish1411 @Kushal-2002 @vaishnavighiradkar you can create this issue separately(only one from you) !
And assign it to yourself !
make sure that duplicate calculators are not allowed !
And remember that the rule is `first come first serve` .
