### ISSUE TITLE
[Create New Issue]: UI - Simple Arithmetic Calculator

### ISSUE THREAD

**Issue by vardhinii** [vasu-1/CalcHub#43]
### Calculator Functions

Description:
I will improve the UI of Simple Arithmetic Calculator

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
No Need !
pick the calculator that solve a mathematical problem !
Minor changes are not required and they are considered as low level contributions !!
