### ISSUE TITLE
Love Calculator

### ISSUE THREAD

**Issue by VagishaGupta9** [vasu-1/CalcHub#44]
### Calculator Functions

A love calculator is an application that allows you to know how compatible you and your partner are and how strong shall be the depth of love between you and your dear one.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
![image](https://user-images.githubusercontent.com/76911582/156207263-0f1ee22d-b6d4-4355-93dd-ff7b502919a1.png)
