### ISSUE TITLE
Scientific Calculator

### ISSUE THREAD

**Issue by abhi1e9-1e10** [vasu-1/CalcHub#5]
### Calculator Functions

This scientific calculator can perform following operations which are listed below: 
 

Square root
Percentage
Factorial
Constants (pie, euler constant, log2 base e, log 10 base e)
Exponent
log base 2, 10, e
Power
Sin, Tan, Cos (enter angle in radians )

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by 1ananya3** [comment]
I am a participant of GSSOC'22. I want to work on this issue. Can you please assign me?

**Comment by Kushal-2002** [comment]
I am a GSSOC'22 participant, I want to work on this issue. I can make this calculator using java script.

**Comment by vasu-1** [comment]
@abhi1e9-1e10  as of now I am deleting this issue as you have already one opened issue !
You can create another issue after your issue will be fixed !
In case of any queries reach out to me on discord !

@1ananya3  @Kushal-2002 you can create this issue separately(only one from you) !
And assign it to yourself !
make sure that duplicate calculators are not allowed !
And remember that the rule is `first come first serve` .
