### ISSUE TITLE
docs: fix Code of conduct

### ISSUE THREAD

**Issue by Pradumnasaraf** [vasu-1/CalcHub#50]
### Changes
code of conduct is not working due to being present in the wrong directory or extension is not correct

#### Due to that we are also missing out on some checks on the community guidelines checklist

![Screenshot from 2022-03-02 09-34-20](https://user-images.githubusercontent.com/51878265/156292930-83cd46c7-9b59-44f3-82ac-ad30cd8df0f7.png)

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
Not Needed!
Your job is to build a unique calculator!

Thanks for your interest!
