### ISSUE TITLE
Complement Calculator

### ISSUE THREAD

**Issue by DhruviSherathiya** [vasu-1/CalcHub#6]
### Calculator Functions

This project's main goal is to find the complements of a given number. For each given input, it can calculate one's complement or two's complement. It accepts data in binary, hexadecimal, or decimal formats.

I'm contributor in GSSOC22, can you assign this issue to me?

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
You can assign this issue to yourself by typing `/assign` in the comment !!
