### ISSUE TITLE
Tip Calculator

### ISSUE THREAD

**Issue by yashikhare** [vasu-1/CalcHub#7]
### Calculator Functions

A Tip Calculator which takes billing amount, type of service, and a number of persons as input. 
As per the three inputs it generates a tip for the serving person.

I'm contributor in GSSOC22, can you please assign this issue to me?

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
You can assign this issue to yourself by typing `/assign` in the comment !!

**Comment by thisisharsh7** [comment]
hello @vasu-1 can I work on this issue?

**Comment by yashikhare** [comment]
Hello, actually I have made a pull request, please merge it and please give reviews about the same.
