### ISSUE TITLE
Modified UI for Age Calculator

### ISSUE THREAD

**Issue by shrutig-287** [vasu-1/CalcHub#72]
### Calculator Functions

The current age calculator accepts birthday as the input, displays current date and outputs age. But the User Interface can be improved to a great extent. Please assign this issue to me so that I can make the necessary changes.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by harinadh76** [comment]
Is anyone working with this issue !!

**Comment by shrutig-287** [comment]
yes @harinadh76
