### ISSUE TITLE
Better UI & mobile responsiveness for BaseX calculator

### ISSUE THREAD

**Issue by hk2257853** [vasu-1/CalcHub#77]
### Calculator Functions

Will be great if I can improve the UI & mobile responsiveness for the BaseX calculator. Thank you 

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by bhavyapathak20** [comment]
@vasu-1 
I would like to collaborate with @hk2257853 on this project
My Skills in web development :

1)HTML
2)CSS
3)Bootstrap
4)Javascript
5)Jquery

My experience :
5+ months of experience in UI design.
Worked on Hands-on projects. My Github repo shows it
