### ISSUE TITLE
Binary Input/Output Calculator

### ISSUE THREAD

**Issue by Arch0125** [vasu-1/CalcHub#85]
### Calculator Functions

Description
The binary input/output calculator takes inputs in binary format and can perform binary addition,subtraction, multiplication and division based on users input.

Screenshot:
![Screenshot from 2022-03-04 21-29-02](https://user-images.githubusercontent.com/72722967/156798008-6e41bbe2-0ce5-4372-9692-4a02030c4614.png)

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by vasu-1** [comment]
There is already one issue https://github.com/vasu-1/CalcHub/issues/28
We can't accept it !

`first come first serve`

Sorry for that !
