### ISSUE TITLE
Body Mass Index

### ISSUE THREAD

**Issue by Mujeeb-shaikh7** [vasu-1/CalcHub#91]
### Calculator Functions

This calculator calculates body mass index of a person

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by Manik-Aggarwal** [comment]
I would like to work on this issue, please assign it to me

**Comment by Priyanshu9548** [comment]
Hi,i am a GSSOC Contributor, i would like to work on this issue. please assign this issue to me.

**Comment by kakkarot0** [comment]
Hi I would love to work on this issue. Please assign it to me
